use_frameworks!

target 'NightFoxHelper_Example' do
  pod 'NightFoxHelper', :path => '../'

  target 'NightFoxHelper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
